//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为, 并且如果
//     重新生成代码, 这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xylia.Preview.Data {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类, 用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员, 请编辑 .ResX 文件, 然后重新运行 ResGen
    // (以 /str 作为命令选项), 或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Public {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Public() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xylia.Preview.Properties.AnalyseSection.Public", typeof(Public).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture Property, 对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;table&gt;
        ///	&lt;public &gt;
        ///		&lt;record alias=&quot;attach-ability&quot;&gt;
        ///			&lt;case alias=&quot;none&quot; default=&quot;y&quot; /&gt;
        ///			&lt;case alias=&quot;attack-power-creature-min-max&quot; name=&quot;攻击&quot; /&gt;
        ///			&lt;case alias=&quot;pve-boss-level-npc-attack-power-creature-min-max&quot; name=&quot;降魔攻击力&quot; /&gt;
        ///			&lt;case alias=&quot;pvp-attack-power-creature-min-max&quot; name=&quot;PVP攻击力&quot; /&gt;
        ///			&lt;case alias=&quot;attack-hit-value&quot; name=&quot;命中&quot; /&gt;
        ///			&lt;case alias=&quot;attack-critical-value&quot; name=&quot;暴击&quot; /&gt;
        ///			&lt;case alias=&quot;attack-critical-damage-value&quot; name=&quot;暴击伤害&quot; /&gt;
        ///		 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;table&gt;
        ///	&lt;public name=&quot;creature_field&quot; &gt;
        ///		&lt;record alias=&quot;creature_field_20&quot; version=&quot;20200630&quot;&gt;
        ///			&lt;case alias=&quot;creature_field_none&quot; default=&quot;y&quot; /&gt;
        ///			&lt;case alias=&quot;world-id&quot; /&gt;
        ///			&lt;case alias=&quot;race&quot; /&gt;
        ///			&lt;case alias=&quot;sex&quot; /&gt;
        ///			&lt;case alias=&quot;job&quot; /&gt;
        ///			&lt;case alias=&quot;appearance1&quot; /&gt;
        ///			&lt;case alias=&quot;appearance2&quot; /&gt;
        ///			&lt;case alias=&quot;appearance3&quot; /&gt;
        ///			&lt;case alias=&quot;appearance4&quot; /&gt;
        ///			&lt;case alias=&quot;appearance5&quot; /&gt;
        ///			&lt;case alias=&quot;appearance6&quot; /&gt;
        ///			&lt;case alias= [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string creature_field {
            get {
                return ResourceManager.GetString("creature_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;table&gt;
        ///	&lt;public name=&quot;Effect.Type&quot; &gt;
        ///		&lt;record alias=&quot;type-seq_20&quot; version=&quot;20200101&quot;&gt;
        ///			&lt;case key=&quot;0&quot; alias=&quot;none&quot; default=&quot;y&quot; /&gt;		
        ///			&lt;case key=&quot;1&quot; alias=&quot;accumulated-damage-to-anyone&quot; /&gt;
        ///			&lt;case key=&quot;2&quot; alias=&quot;accumulated-damage-from-1&quot; /&gt;
        ///			&lt;case key=&quot;3&quot; alias=&quot;accumulated-damage-from-2&quot; /&gt;
        ///			&lt;case key=&quot;4&quot; alias=&quot;accumulated-damage-from-3&quot; /&gt;
        ///			&lt;case key=&quot;5&quot; alias=&quot;melee-physical-attack&quot; /&gt;
        ///			&lt;case key=&quot;6&quot; alias=&quot;melee-physical-attack-hate&quot; /&gt;
        ///			 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string effect_type {
            get {
                return ResourceManager.GetString("effect_type", resourceCulture);
            }
        }
    }
}
